### ISSUE TITLE
-b option truncates output at 10k

### ISSUE THREAD

**Issue by NicRamb** [jwalabroad/VariantBam#20]
Hi! I downloaded variantbam through conda (bioconda channel) and I am experiencing the issue where it works until about 10k on the reference, and then filters out all the reads. I saw that this was solved and the issue was closed. But I tried all versions on bioconda (1.3.0, 1.4.3, 1.4.4a) and keep getting this error. Is there a way to overcome this through conda?

Thanks,
Nicola

**Comment by walaj** [comment]
Closing as I don't manage bioconda repos of this, so would recommend just installing directly from updated repos.
