### ISSUE TITLE
Installing VariantBam

### ISSUE THREAD

**Issue by maingoc303** [jwalabroad/VariantBam#21]
Dear Author,
When installing VariantBam, I got the error message like this: 
"""
configure: creating ./config.status
config.status: creating Makefile
config.status: error: cannot find input file: `SnowTools/src/Makefile.in'
"""
Can you please help to check?

**Comment by walaj** [comment]
This looks like an old checkout? Works fine with `git clone --recursive https://github.com/walaj/VariantBam`.
