### ISSUE TITLE
Possible problem with use case 4

### ISSUE THREAD

**Issue by maplesond** [jwalabroad/VariantBam#3]
I'm trying to run use case 4 on my own datasets,I'm not getting any output when the '-x' option is used.  I expected just some count information rather than the BAM.  Removing the '-x' and replacing with '-o' behaves as expected.

**Comment by maplesond** [comment]
After looking at this a bit closer.  I think the example use case should be updated to include the '-c <counts_file>' option as well '-x'

**Comment by walaj** [comment]
Good catch, the option parser was not grabbing the argument to -x. This is fixed in the latest commit. The   proper usage is now as described in case 4.
