### ISSUE TITLE
Referring to target sequences

### ISSUE THREAD

**Issue by maplesond** [jwalabroad/VariantBam#4]
In the quickstart guide it suggests putting in a user BAM and isolating a region with -g 1:100,000,000-100,001,000.  For some BAMs the target sequence name contains long complex strings, which can still work but require that they are wrapped in quotes: e.g: "variant bowtie2.sorted.bam -g 'gi|253972022|gb|CP000819.1|':1-1000000 -r mapq[20,30] -c counts.tsv -o mini.bam -v".  This should be made clear in the quickstart guide and in the general documentation.  For the quickstart guide you would work around this by providing a real (small) BAM file in your examples directory.

Also it would be nice if we could use the reference id, as well as the reference name to refer to a reference sequence, although care would need to be taken to avoid conflicts in the case where reference names are numeric.

**Comment by walaj** [comment]
Thanks Daniel, good suggestions on all accounts. I'm modifying the documentation as suggested and adding a small example BAM (with non-protected data). Thanks for a careful look at the docs.
-Jeremiah
