### ISSUE TITLE
Can't build in boost static libs from default install locations

### ISSUE THREAD

**Issue by maplesond** [jwalabroad/VariantBam#6]
The system works fine if --with-boost is specified.  However, if boost is installed into the default system locations: /usr/local for example, then the Makefile won't try to link against the static libs.  Instead it tries to find the libraries off the root "/".

**Comment by walaj** [comment]
Hoping it works now. I had some issues with linking the unit test libraries, and I guess it made it not as portable as it should be. If GCC knows to look by default in /usr/local, I think this will work

**Comment by maplesond** [comment]
Ok, cool.  I'll check it out next time I recompile.  I can your interested I have modified a version of ax_boost m4 macros to handle boost static libraries.  See here: https://github.com/TGAC/KAT/tree/develop/m4.  I found this the easiest way to check for boost binaries, without requiring dynamic linking.  May or may not be useful for you.

**Comment by walaj** [comment]
Thanks for the macros and for the very helpful suggestions on how to improve the software. I'll definitely look into how to use these for easier builds.

**Comment by walaj** [comment]
Finally marking this as solved. I have removed all dependencies on Boost.
